---
abstract: 'Invoke callbacks when the stash code is being compiled in changes'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  B::Hooks::OP::Check: 0.14
configure_requires:
  B::Hooks::OP::Check: 0.14
  ExtUtils::Depends: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-OP-Check-StashChange
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check: 0.14
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
