---
abstract: 'Invoke callbacks when the stash code is being compiled in changes'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  B::Hooks::OP::Check: 0.14
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  B::Hooks::OP::Check: 0.14
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Hooks-OP-Check-StashChange
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check: 0.14
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=B-Hooks-OP-Check-StashChange
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rafl/b-hooks-op-check-stashchange.git
version: 0.06
